<a href="https://colab.research.google.com/github/ashiqurrahmankhan21st/StudyOnSV/blob/main/Sexual_Violanceipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# prompt: connect to github and read private data from github

# Install necessary libraries if not already installed
!pip install PyGithub

import github
from github import Github
import pandas as pd

# You need to replace 'YOUR_GITHUB_TOKEN' with your actual GitHub personal access token.
# Make sure your token has the necessary permissions to access the private repository.
# For security reasons, do not hardcode your token directly in the notebook.
# Consider using Google Colab Secrets for storing sensitive information.
# Example: In the Colab Secrets panel, add a new secret named 'GITHUB_TOKEN' with your token as the value.
# Then access it using: from google.colab import userdata; token = userdata.get('GITHUB_TOKEN')

# For demonstration purposes, I'm using a placeholder.
# Replace with your actual token retrieval method.
# token = 'YOUR_GITHUB_TOKEN' # Replace with your actual token or retrieve from Secrets
try:
    from google.colab import userdata
    token = userdata.get('GITHUB_TOKEN')
except Exception as e:
    print(f"Could not retrieve GitHub token from Colab Secrets: {e}")
    token = 'YOUR_GITHUB_TOKEN' # Fallback - replace with your actual token

if token == 'YOUR_GITHUB_TOKEN':
    print("Warning: Replace 'YOUR_GITHUB_TOKEN' with your actual token or use Colab Secrets.")
    # You might want to raise an error or exit if the token is not set correctly.
    # raise ValueError("GitHub token not configured.")

# Authenticate with GitHub
try:
    g = Github(token)
except Exception as e:
    print(f"Error authenticating with GitHub: {e}")
    # Handle the authentication error appropriately

# Replace 'YOUR_USERNAME' and 'YOUR_REPOSITORY' with your GitHub username and repository name
username = 'ashiqurrahmankhan21st'
repository_name = 'StudyOnSV'
file_path = 'sexual violence.csv'

try:
    # Get the repository
    repo = g.get_user(username).get_repo(repository_name)

    # Get the file content (this reads the raw content of the file)
    content = repo.get_contents(file_path).decoded_content.decode()

    # Read the content into a Pandas DataFrame
    from io import StringIO
    df_private = pd.read_csv(StringIO(content))

    # Display the head of the DataFrame
    display(df_private.head())

except github.GithubException as e:
    print(f"Error accessing GitHub repository or file: {e}")
    print("Please ensure:")
    print(f"- The repository '{repository_name}' exists under the user '{username}'.")
    print(f"- The file path '{file_path}' is correct.")
    print("- Your GitHub token has permissions to access this private repository.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Requirement already satisfied: PyGithub in /usr/local/lib/python3.11/dist-packages (2.6.1)
Requirement already satisfied: pynacl>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub) (1.5.0)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub) (2.32.3)
Requirement already satisfied: pyjwt>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (2.10.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub) (4.14.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub) (2.4.0)
Requirement already satisfied: Deprecated in /usr/local/lib/python3.11/dist-packages (from PyGithub) (1.2.18)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (43.0.3)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from pynacl>=1.4.0->PyGithub) (1.17.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub) (2025.7.14)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from Deprecated->PyGithub) (1.17.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.22)
Could not retrieve GitHub token from Colab Secrets: Secret GITHUB_TOKEN does not exist.
Warning: Replace 'YOUR_GITHUB_TOKEN' with your actual token or use Colab Secrets.
Error accessing GitHub repository or file: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest", "status": "401"}
Please ensure:
- The repository 'StudyOnSV' exists under the user 'ashiqurrahmankhan21st'.
- The file path 'sexual violence.csv' is correct.
- Your GitHub token has permissions to access this private repository.

In [9]:
import numpy as np
import pandas as pd
import requests

In [26]:
url = "https://github.com/ashiqurrahmankhan21st/StudyOnSV/blob/main/sexual%20violence.xlsx?raw=true"

response = requests.get(url)
response.raise_for_status() # Raise an exception for bad status codes
# Read the content into a Pandas DataFrame
from io import BytesIO
df = pd.read_excel(BytesIO(response.content))
df.shape

(2362, 17)

In [27]:
df.head()

,id,ageband,victim_type,victim_offerder_relation,incident_upazila,incident_district,incident_divison,part_of_the_day,incident_date,year,month,day,temperature,season,sexual_violence_type,source,news link
0,1,19-35,children,unacquaintance,hathazari,chattogram,chattogram,NaN,2018-09-14 00:00:00,2018.0,september,friday,80.0,rainy,rape followed by murder,The Daily Star,https://www.thedailystar.net/news/bangladesh/c...
1,2,19-35,children,acquaintance,shibganj,bogura,rajshahi,noon,2018-04-25 00:00:00,2018.0,april,wednesday,91.0,hot,rape,The Daily Star,https://www.thedailystar.net/country/6-years-o...
2,3,19-35,women,acquaintance,rupganj,narayaganj,dhaka,afternoon,2018-03-10 00:00:00,2018.0,march,friday,90.0,hot,rape,The Daily Star,https://www.thedailystar.net/backpage/22-year-...
3,4,19-35,children,NaN,alikadom bazar,bandarban,chattogram,night,2018-04-12 00:00:00,2018.0,april,thursday,91.0,hot,rape,The Daily Star,https://www.thedailystar.net/country/bandarban...
4,5,19-35,children,acquaintance,gabtoli,bogura,rajshahi,evening,2019-04-19 00:00:00,2019.0,april,friday,86.0,hot,rape,The Daily Star,https://www.thedailystar.net/country/child-rap...

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2362 entries, 0 to 2361
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        2362 non-null   int64
 1   ageband                   2209 non-null   object
 2   victim_type               2352 non-null   object
 3   victim_offerder_relation  2330 non-null   object
 4   incident_upazila          2057 non-null   object
 5   incident_district         2312 non-null   object
 6   incident_divison          2357 non-null   object
 7   part_of_the_day           1731 non-null   object
 8   incident_date             2136 non-null   object
 9   year                      2345 non-null   float64
 10  month                     2305 non-null   object
 11  day                       2136 non-null   object
 12  temperature               2137 non-null   float64
 13  season                    2315 non-null   object
 14  sexual_violence_type      2362 non-null   object
 15  source                    2362 non-null   object
 16  news link                 2362 non-null   object
dtypes: float64(2), int64(1), object(14)
memory usage: 313.8+ KB

In [29]:
df1 = df.dropna()
df1.shape

(1412, 17)

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1412 entries, 1 to 2361
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        1412 non-null   int64
 1   ageband                   1412 non-null   object
 2   victim_type               1412 non-null   object
 3   victim_offerder_relation  1412 non-null   object
 4   incident_upazila          1412 non-null   object
 5   incident_district         1412 non-null   object
 6   incident_divison          1412 non-null   object
 7   part_of_the_day           1412 non-null   object
 8   incident_date             1412 non-null   object
 9   year                      1412 non-null   float64
 10  month                     1412 non-null   object
 11  day                       1412 non-null   object
 12  temperature               1412 non-null   float64
 13  season                    1412 non-null   object
 14  sexual_violence_type      1412 non-null   object
 15  source                    1412 non-null   object
 16  news link                 1412 non-null   object
dtypes: float64(2), int64(1), object(14)
memory usage: 198.6+ KB

In [74]:
df1.iloc[:,1].value_counts()

ageband
0-18     860
19-35    477
35+       75
Name: count, dtype: int64